mod 'boxen',  '3.9.1', :github_tarball => 'boxen/puppet-boxen'
mod 'module-data', '0.0.1', :github_tarball => 'ripienaar/puppet-module-data'
mod 'stdlib', '4.1.0', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
